# Generated by Django 5.1.15 on 2026-10-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_organisation_organogram_parsing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organisations.organisation')),
                ('recorded_by', models.ForeignKey(blank=True, help_text="Set only when a manager or HR enters or corrects this record on the employee's behalf.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organisation', 'user', '-date'], name='attendance__organis_81bddb_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user', 'date'), name='one_attendance_record_per_user_per_day')],
            },
        ),
    ]
