# Generated by Django 5.1.15 on 2026-04-27 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
        ('organisations', '0002_alter_organisation_organogram_file'),
        ('tasks', '0002_alter_task_created_by_alter_taskoutput_submitted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organisation', 'user', '-started_at'], name='attention_a_organis_56cb53_idx'),
        ),
        migrations.AddIndex(
            model_name='breaklog',
            index=models.Index(fields=['organisation', 'user', '-started_at'], name='attention_b_organis_8329af_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['organisation', 'user', '-started_at'], name='attention_t_organis_f2c9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['organisation', 'task', '-started_at'], name='attention_t_organis_d91b57_idx'),
        ),
    ]
