# Generated by Django 5.1.15 on 2026-04-27 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_alter_organisation_organogram_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(choices=[('TASK_COMPLETION_RATE', 'Task Completion Rate'), ('ON_TIME_DELIVERY', 'On-Time Delivery'), ('DEPT_PRODUCTIVITY', 'Department Productivity')], max_length=32)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target percentage 0-100', max_digits=6)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='QUARTERLY', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional — if set, target applies to this department; else org-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='organisations.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='organisations.organisation')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organisation', 'metric', 'period', 'department')},
            },
        ),
    ]
