# Generated by Django 5.1.15 on 2026-04-27 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_created_by_alter_message_sender'),
        ('organisations', '0002_alter_organisation_organogram_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organisation', 'conversation', 'created_at'], name='messaging_m_organis_386cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organisation', 'sender', 'created_at'], name='messaging_m_organis_9508c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='messaging_m_convers_211665_idx'),
        ),
    ]
