# Generated by Django 5.1.15 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organogram_file',
            field=models.URLField(blank=True, help_text='URL to organogram file (Cloudinary or S3)', max_length=500),
        ),
    ]
