# Generated by Django 5.1.15 on 2026-03-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('plan_tier', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('payment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
