# Generated by Django 5.1.15 on 2026-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card on file', max_length=4),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='gateway_customer_id',
            field=models.CharField(blank=True, help_text='External payment gateway customer ID (e.g. Stripe cus_xxx)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, help_text='External payment gateway subscription ID', max_length=255, null=True),
        ),
    ]
