# Generated by Django 5.1.15 on 2026-03-27 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type', models.CharField(choices=[('JD_DRAFT', 'JD Draft'), ('COACHING_TIP', 'Coaching Tip'), ('TASK_SUMMARY', 'Task Summary'), ('PROJECT_SUMMARY', 'Project Summary'), ('MILESTONE_EXTRACTION', 'Milestone Extraction'), ('REPORT_DRAFT', 'Report Draft'), ('NL_SEARCH', 'Natural Language Search')], max_length=30)),
                ('input_data', models.JSONField(default=dict)),
                ('output_content', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_outputs', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Output',
                'verbose_name_plural': 'AI Outputs',
                'ordering': ['-created_at'],
            },
        ),
    ]
