# Generated by Django 5.1.15 on 2026-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0003_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aioutput',
            name='output_type',
            field=models.CharField(choices=[('JD_DRAFT', 'JD Draft'), ('COACHING_TIP', 'Coaching Tip'), ('TASK_SUMMARY', 'Task Summary'), ('PROJECT_SUMMARY', 'Project Summary'), ('MILESTONE_EXTRACTION', 'Milestone Extraction'), ('REPORT_DRAFT', 'Report Draft'), ('NL_SEARCH', 'Natural Language Search'), ('POLICY_DESCRIPTION', 'Policy Description')], max_length=30),
        ),
    ]
