# Generated by Django 5.1.15 on 2026-04-27 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='succeeded_by',
            field=models.ForeignKey(blank=True, help_text='Successor — once set, this user is treated as the predecessor for institutional-memory queries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to=settings.AUTH_USER_MODEL),
        ),
    ]
