# Generated by Django 5.1.15 on 2026-05-31 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='succeeded_by',
            field=models.ForeignKey(blank=True, help_text='Successor — assigned while active for handover planning; once this user is inactive, the successor inherits their tasks and records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to=settings.AUTH_USER_MODEL),
        ),
    ]
