# Generated by Django 5.1.15 on 2026-05-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_by_alter_taskoutput_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskreview',
            options={'ordering': ['-created_at']},
        ),
    ]
